### ISSUE TITLE
Meet-up: 2017-04-12

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/playbook#1]
* Venue: [CivilCode Inc.](https://www.google.ca/maps/place/CivilCode+Inc./@45.519507,-73.589514,17z/data=!4m12!1m6!3m5!1s0x4cc91bd33fcc7fcf:0x723010dadf3ba4f2!2sCivilCode+Inc.!8m2!3d45.519507!4d-73.58732!3m4!1s0x4cc91bd33fcc7fcf:0x723010dadf3ba4f2!8m2!3d45.519507!4d-73.58732)
* Presenters: TBA

### ASAP

- [x] Book the venue
- [x] Schedule talks
- [x] Identify sponsor
- [x] Purchase video camera / mic

###  Minus 2 weeks (03-29)

- [x] Determine agenda
- [x] Publish event on Meetup.com
- [x] Tweet the event
- [x] Plan drinks and food

### Minus 1 week (04-05)

- [x] Check with the speakers if they need anything
- [ ] Check with the sponsors for announcements

### On the day (04-12)

- [x] Order the food
- [x] Buy the drinks
- [x] Prepare recording equipment

### The day after the event  (04-13)

- [ ] Write a follow-up on Meetup.com
- [x] Email the sponsors to say thank you
- [x] Email the venue to say thank you
- [x] Email the speakers to say thank you

### ASAP

- [x] Produce and post presentation videos
- [ ] Review checklist from Playbook to incorporate new items

### Follow-up

- [x] Add items to Playbook checklist for sponsorship commitments

**Comment by nicholasjhenry** [comment]
## Program

| Time | Item  |
| --- | --- |
| 18:30 | Mingle |
|       | A chance to meet and chat with other Elixir enthusiasts before the presentations start. Help yourself to drinks and snacks. |
| 19:00 | Welcome to Montreal Elixir by Nicholas Henry |
|       | An introduction to the Montreal Elixir Meet-up outlining the vision for the group and how you can contribute. |
| 19:20 | Break |
| 19:30 | Collections in Elixir presented by Hugo Frappier |
|       | Elixir offers many ways to store data in a collection: tuples, lists, keyword lists, maps, and structs. Let's review each of these and discuss their appropriate use cases. |
| 19:50 | Break |
| 20:00 | OTP, Concurrency and Testing Strategies by Adrián Mugnolo |
|       | The goal is to introduce generic servers, then cover testing strategies for starting, stopping, state updates, sync and async requests. |
| 20:20 | Open Announcements |
|       | Would you like to introduce yourself to the group and what you hope to learn? Are you a company looking to hire an Elixir developer? Please share! |
| 20:30 | Finish |
|       | This is not a hard stop; please feel free to hang out and chat. |

**Comment by nicholasjhenry** [comment]
@frahugo Can you please review the Meet-up program above please?

**Comment by frahugo** [comment]
All good.
