### ISSUE TITLE
Meet-up: 2017-05-10

### ISSUE THREAD

**Issue by frahugo** [montrealelixir/playbook#11]
* Venue: Shopify

## Presenters

| speaker | status | title | description | bio | length |
| --- | --- | --- | --- | ---| ---|
| JP | confirmed | Elixir for Node developer | Running in backends, Node.js and Elixir/OTP both solve very similar problems. The goal of the presentation is to explain how Elixir/OTP attacks those problems compared to Node.js. | @jpbecotte JPB is a full stack web developer, a former teacher and a startup enthusiast who has a robust background with Javascript. | Demi |
| JN | confirmed | HOWTO: Contribute to and create open source projects with Elixir  | A great way to learn a new language is by contributing! In this talk I will share some techniques I've learned that make this easier.  | @joshnuss  Software developer @shopify. Has made multiple attempts at building UAVs - all ended in crashes and/or fireballs. | Demi |

## Program

| Time | Item  |
| --- | --- |
| 18:30 | Mingle |
|       | A chance to meet and chat with other Elixir enthusiasts before the presentations start. Grab a bite to eat. |
| 19:00 | Welcome and Community Updates by Nicholas Henry |
|       | A review of points of interest in our local community and Elixir in general. |
| 19:20 | Break |
| 19:25 | Elixir for Node developer by Jean-Pierre Bécotte |
|       | Running in backends, Node.js and Elixir/OTP both solve very similar problems. The goal of the presentation is to explain how Elixir/OTP attacks those problems compared to Node.js. |
| 19:50 | Break |
| 19:55 | HOWTO: Contribute to and create open source projects with Elixir by Joshua Nussbaum |
|       | A great way to learn a new language is by contributing! In this talk I will share some techniques I've learned that make this easier. |
| 20:20 | Open Announcements |
|       | Would you like to introduce yourself to the group and what you hope to learn? Are you a company looking to hire an Elixir developer? Please share! |
| 20:30 | Finish |
|       | See you in June! |

### ASAP

- [x] Book the venue
- [x] Schedule talks
- [x] Identify sponsor
- [x] Apply for liquor license

###  Minus 2 weeks (04-26)

- [x] Determine agenda
- [x] Publish event on Meetup.com
- [x] Tweet the event
- [x] Plan drinks and food

### Minus 1 week (05-03)

- [x] Check with the speakers if they need anything
- [x] Check with the sponsors for announcements

### On the day (05-10)

- [x] Order the food
- [x] Buy the drinks
- [x] Prepare recording equipment
- [x] Request an update on RSVP's

> Hey, everybody, we're looking forward to seeing you tonight. If you're unable to make it, can you please update your RSVP as a "No". This will be a big help with planning. Hopefully, we'll see you in June instead.

### The day after the event  (05-11)

- [x] Write a follow-up on Meetup.com
- [x] Email the sponsors to say thank you
- [x] Email the venue to say thank you
- [x] Email the speakers to say thank you

### ASAP

- [x] Produce and post presentation videos
- [ ] Review checklist from Playbook to incorporate new items

### Follow-up

- [x] Add items to Playbook checklist for sponsorship commitments

**Comment by nicholasjhenry** [comment]
# Meet our obligations to Shopify for sponsorship

## On-line

- [x] Your company name and link to your website on the event announcement posted on Meetup.com.
- [x] Your logo and link to your website on Meetup.com for up to one year.
- [x] A tweet of appreciation one day after the event from the Montreal Elixir Twitter account.
- [x] Logo included in opening credits of recorded presentations posted on YouTube.

## At the event

- [x] An announcement of appreciation for your sponsorship at the beginning of the meet-up.
- [x] Logo on the event's welcome presentation slide displayed on the venue's visual system (projector or monitor), before and after presentations.
- [x] Priority to make an announcement in the "Open Announcements" section of the meet-up. Any announcement may be a company pitch, communicating job offerings or a product demo.
