### ISSUE TITLE
Setup `montrealelixir` channel on elixir-lang.slack.com

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/playbook#12]
Reference: https://www.meetup.com/montrealelixir/events/238411707/?read=1&_af=event&_af_eid=238411707&https=on

**Comment by xymbol** [comment]
Contacted an admin to check the status for the `#montreal` channel. Should hear back from her shortly. https://elixir-lang.slack.com/archives/C1B4CTMJP/p1492132434009680

**Comment by xymbol** [comment]
Quick update. The `#montreal` channel seems to be [unavailable](https://elixir-lang.slack.com/archives/C1B4CTMJP/p1492530766386144) to admins too:

>Weirdly, it looks like we cant create that channel
>We’re not sure why as no channel with that name exists
>I should have gotten back to you

Meanwhile, I created a `#montrealelixir` channel we can use.

**Comment by nicholasjhenry** [comment]
Thank you for organizing that @xymbol ;-)

- [ ] add slack channel to various on-line properties

**Comment by xymbol** [comment]
New update. I have repeatedly contacted Elixir community Slack admins re this issue. Apparently, Slack support is not getting back to them re the mysteriously missing channel.

![image](https://cloud.githubusercontent.com/assets/13948/25662840/f882dc24-2fe3-11e7-897a-020ddf8cb02d.png)

For now, I would start using `#montrealelixir` and see. If, at some point, local channels got organized and renamed consistently, we would need to move.

@nicholasjhenry If you're okay with this, I would close the issue.

**Comment by nicholasjhenry** [comment]
Thank you, @xymbol 👍
