### ISSUE TITLE
Have a repo for meetup contents?

### ISSUE THREAD

**Issue by xymbol** [montrealelixir/playbook#13]
I think it could be good to have a separate `meetups` repository to discuss meetup content and activities. Having a playbook is a fantastic idea but, seems more targeted to staff: organizers, co-organizers, volunteers, presenters, etc. Attendees would better star a content-centered repo.

**Comment by nicholasjhenry** [comment]
I was thinking the same thing, @xymbol. The repo could contain a summary of past meetups as well. I'll get that setup.

**Comment by xymbol** [comment]
@nicholasjhenry If you get the repo created, I can submit an initial pull-request following what's already in the Playbook. Please let me know!

**Comment by nicholasjhenry** [comment]
We now have a repo for meetups and other events:

https://github.com/montrealelixir/events
