### ISSUE TITLE
RFC: Project nights track for Montreal Elixir

### ISSUE THREAD

**Issue by xymbol** [montrealelixir/playbook#19]
Wanted to submit this proposal for consideration. I have done some of this before and, found it to be very useful for people at all levels. Feedback is welcome!

# Summary

Organize a hands-on, code centered, project nights track for Montreal Elixir meetup.

# Motivation

People learn new things in very own ways. The article about "learning" on Wikipedia classifies 18 different types of learning.

Learning a programming language, libraries and, frameworks is no different. Some people learn from reading books, watching screencasts, attending talks and, others, from actually writing code. In music, there is a word for this kind of learning: étude.

This format is not new. For example, the Ember meetup in New York City runs as many project nights as regular events.

The purpose of these events would be to provide a safe, open, friendly, welcoming environment to sit together, maybe pair, ask questions, learn or teach anything related to Elixir, Erlang and OTP.

# Detailed design

Tentatively, events could follow an agenda like:

- Welcome and messages
- Pair people coaching with those needing help
- Proposed activities
- Sponsor, venue messages
- Goodbye

For example, one event could take place at a coffee shop in downtown Montreal during a weekday evening. The following event could have a different host and move to a company workspace on a Saturday morning with a different host.

# What is it about?

- Bring your own project
- Mob programming
- Code reading
- Open source
- Training wheels

# What is not?

- Prepared talks
- Video recording
- Fixed agenda
- Eating
- Drinking, etc.

# Requirements

- Venue (needs space with tables, not a classroom configuration)
- Connectivity
- Power ports
- Drinking water
- Access to restrooms, etc.

# Unresolved questions

- Coordination with "main" meetup
- Organizers?
- Non-conflicting dates?

**Comment by nicholasjhenry** [comment]
@xymbol Could you post this in the new "events" repo (https://github.com/montrealelixir/events/issues), please? I want to make sure you are attributed to it. And yes, we definitely need to discuss this. Thanks!
