### ISSUE TITLE
Meetup: 2017-06-14

### ISSUE THREAD

**Issue by frahugo** [montrealelixir/playbook#20]
* Venue: Shopify

## Presenters

| speaker | status | title | description | bio | length |
| --- | --- | --- | --- | ---| ---|
| ? | ? | ? | ? | ? |
| ? | ? | ? | ? | ? |

## Program

| Time | Item  |
| --- | --- |
| 18:30 | Mingle |
|       | A chance to meet and chat with other Elixir enthusiasts before the presentations start. Grab a bite to eat. |
| 19:00 | Welcome and Community Updates by Nicholas Henry |
|       | A review of points of interest in our local community and Elixir in general. |
| 19:20 | Break |
| 19:25 | ? |
|       | ? |
| 19:50 | Break |
| 19:55 | ? |
|       | ? |
| 20:20 | Open Announcements |
|       | Would you like to introduce yourself to the group and what you hope to learn? Are you a company looking to hire an Elixir developer? Please share! |
| 20:30 | Finish |
|       | See you in July! |

### ASAP

- [x] Book the venue
- [ ] Schedule talks
- [x] Identify sponsor
- [x] Apply for liquor license

###  Minus 3 weeks (?)

- [x] Apply for liquor permit: [Form](https://www.racj.gouv.qc.ca/en/formulaires-et-publications/forms/alcohol/reunion-permits/application-for-a-reunion-permit.html)

###  Minus 2 weeks (?)

- [ ] Determine agenda
- [ ] Publish event on Meetup.com
- [ ] Tweet the event
- [ ] Plan drinks and food

### Minus 1 week (?)

- [ ] Check with the speakers if they need anything
- [ ] Check with the sponsors for announcements
- [ ] Prepare backup questions

### On the day (?)

- [ ] Order the food
- [ ] Buy the drinks
- [ ] Prepare recording equipment
- [ ] Request an update on RSVP's
- [ ] Print name tags
- [ ] Print "Repeat the question" sign

> Hey, everybody, we're looking forward to seeing you tonight. If you're unable to make it, can you please update your RSVP as a "No". This will be a big help with planning. Hopefully, we'll see you in June instead.

### The day after the event (?)

- [ ] Write a follow-up on Meetup.com
- [ ] Email the sponsors to say thank you
- [ ] Email the venue to say thank you
- [ ] Email the speakers to say thank you

### ASAP

- [ ] Produce and post presentation videos
- [ ] Review checklist from Playbook to incorporate new items

### Follow-up

- [ ] Add items to Playbook checklist for sponsorship commitments

**Comment by frahugo** [comment]
![img_3658](https://cloud.githubusercontent.com/assets/14030/25974088/126d677a-3675-11e7-82c1-f65c012e2613.JPG)

**Comment by frahugo** [comment]
![img_3658](https://cloud.githubusercontent.com/assets/14030/25974114/33a27ec6-3675-11e7-8de3-df235ea64997.JPG)

**Comment by nicholasjhenry** [comment]
Moved to https://github.com/montrealelixir/events/issues/1
