### ISSUE TITLE
Presenters Checklist

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/playbook#7]
- On the Mac, in the notification center:
  - enable "Do not disturb"
  - disable "Night Shift" 

  ![screenshot 2017-04-13 08 25 25](https://cloud.githubusercontent.com/assets/40253/25004532/cf938500-2022-11e7-9cc7-310ac2831338.png)

- in Chrome, [disable notifications](https://support.google.com/chrome/answer/3220216?co=GENIE.Platform%3DDesktop&hl=en)
- no need to do anything in Safari, it's handled by the "Do not disturb" switch in the notification center
- make sure energy saving preferences will not turn off the display after a few minutes

**Comment by xymbol** [comment]
I was hit by this one on Wednesday. Please note that Chrome will **still** display notifications disregarding settings on a Mac. Need to explicitly [turn them off](https://support.google.com/chrome/answer/3220216?co=GENIE.Platform%3DDesktop&hl=en).

![chrome-notifications](https://cloud.githubusercontent.com/assets/13948/25046042/39c821a8-20fd-11e7-9db3-fa67443d096f.png)
