### ISSUE TITLE
Recommendations for Presentation preparation

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/playbook#9]
- dry-run
- how to estimate the length of your presentation (by the number of slides)
- timing your presentation

**Comment by xymbol** [comment]
Also hit by this one. But, I'm sure we'll know better once we know more about the attendance. IMO making presentations too strict, and thus more expensive to prepare, usually goes against the number of proposals, the opportunity to improvise and, adapting to questions, etc.

**Comment by xymbol** [comment]
Re presentation length, code-centered presentations, are harder to anticipate, unless video is recorded for each step which probably makes them unaffordable as meetup content. Well-known podcaster Avdi Grimm once [estimated](http://www.virtuouscode.com/2013/01/21/my-screencasting-process/) this:

>I’d estimate the whole process takes roughly 2-4 hours for one ~5 minute episode. 

One can go with 1-3 slides per minute, depending on the concepts being covered, pace, level of detail, if open to questions, etc. If a faster-paced, minimalist approach is taken, one per 20 seconds is doable, like the format used in [PechaKucha](http://www.virtuouscode.com/2013/01/21/my-screencasting-process/) events.

**Comment by nicholasjhenry** [comment]
>  IMO making presentations too strict, and thus more expensive to prepare, usually goes against the number of proposals, the opportunity to improvise and, adapting to questions, etc.

One way adjusting this is to provide a range (e.g. 20-30 mins including questions). Conferences have limited time-slots, a schedule and not sure why meet-ups would be any different. It's also about setting expectations for your audience (i.e how much time am I investing in this?) and respecting their time. I think leaving questions to the end also helps on controlling the time. Having shorter options such as 5 and 15 mins gives presenters something that takes less presentation and should be easier to predicate time.

Certainly interested in what other members think. Please comment!
